version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - NEXT_PUBLIC_WS_URL=ws://localhost:3001
      - NEXT_PUBLIC_AI_SERVICE_URL=http://localhost:8001
    depends_on:
      - backend
      - ai-service

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - FRONTEND_URL=http://localhost:3000
      - AI_SERVICE_URL=http://ai-service:8001
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - ai-service

  ai-service:
    build: ./ai-service
    ports:
      - "8001:8001"
    environment:
      - PYTHONPATH=/app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
