version: "3.9"

services:
  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    container_name: ai-service
    env_file:
      - .env
    ports:
      - "8001:8001"
    depends_on:
      - redis
      - smtp
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ai-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  smtp:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    restart: unless-stopped
